[programs.localnet]
money_stream_program = "2m2pMvmHSkHnvc8VS492WeoxMqnyou3mdPCQxvocDXPx"

[registry]
url = "https://eter.io"

[provider]
cluster = "devnet"
wallet = "/home/ibritvic/test-solana-wallet1/my-keypair.json"

[scripts]
test = "mocha -t 1000 tests/"
