[programs.localnet]
money_stream_program = "5xCzmy6UvLQJX7GBckN4q5EaC4ypsLhAhM9jhdfKXBR1"

[registry]
url = "https://eter.io"

[provider]
cluster = "devnet"
wallet = "/home/ibritvic/test-solana-wallet1/my-keypair.json"

[scripts]
test = "mocha -t 1000 tests/"
